### ISSUE TITLE
Gettext

### ISSUE THREAD

**Issue by helderco** [docker-library/django#11]
How about including gettext?

**Comment by yosifkit** [comment]
It is available from the python standard lib. You probably just need an import?

```console
$ docker run -it --rm django python
Python 3.4.3 (default, Oct 23 2015, 22:19:50) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gettext
>>> gettext.gettext("Hello, World!")
'Hello, World!'
>>> 
```

**Comment by helderco** [comment]
I'm actually talking about GNU gettext. 

From https://docs.djangoproject.com/en/1.8/topics/i18n/translation/#message-files:

> The makemessages command (and compilemessages discussed later) use commands from the GNU gettext toolset: xgettext, msgfmt, msgmerge and msguniq.

> The minimum version of the gettext utilities supported is 0.15.

**Comment by yosifkit** [comment]
I see; that seems valid to add to the image.  Want to make a PR?
