### ISSUE TITLE
Tutorial doesn't work.

### ISSUE THREAD

**Issue by MMKnight** [docker-library/django#15]
I use 'docker run --name myapp -t poll'. I greped the IP but it won't work. The Dockerfile installed same directory as manage.py .

**Comment by yosifkit** [comment]
If you are on a Mac or Windows, then you need to have a `-p 8000:8000` and hit the IP of the VM at port 8000.

**Comment by yosifkit** [comment]
We have deprecated the django image in favor of just the python image: https://github.com/docker-library/docs/pull/630.
