### ISSUE TITLE
pip install fails if requirements.txt includes "-r path/to/more/requirements.txt"

### ISSUE THREAD

**Issue by lbjay** [docker-library/django#7]
The `requirements.txt` in my app root only contains the line:

```
-r requirements/foo.txt
```

So the 'django:onbuild' image doesn't work for me because the `Dockerfile` only copies the `requirements.txt` file before running `pip install`. Could it not be simplified to just:

```
ONBUILD COPY . /usr/src/app
ONBUILD RUN pip install -r requirements.txt
```

**Comment by yosifkit** [comment]
The current ordering is to maximize docker caching.  Doing a docker build, you don't want to have to wait for `pip install` every time that you change something in a python script.

This is the limitation of the onbuild images. They are meant for simple projects to just get you running. For more complicated setups (ie, that have multiple requirements files), we recommend just copying the items from the onbuild Dockerfile, removing ONBUILD from the commands, and then adding in your custom steps (like `COPY requirements/foo.txt /usr/src/app/reqirements/foo.txt`). 

(related onbuild discussions: https://github.com/docker-library/ruby/issues/35, https://github.com/docker-library/rails/issues/28)

**Comment by lbjay** [comment]
Okey-doke. I'll carry on with my copied/modified Dockerfile. Thanks for the illumination.
