### ISSUE TITLE
Update pip before all

### ISSUE THREAD

**Issue by rodrigobraga** [docker-library/django#8]
Hi

I'm using Dockerfile for django:python2-onbuild and I received the message below; is possible force update before all?!

```
You are using pip version 6.1.1, however version 7.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by yosifkit** [comment]
The message is just a warning.  We try to keep `pip` updated in the images and the new `python` and `django` images are currently building on the build server with `7.0.1`. If you always need the most up to date `pip` I would suggest copying the steps in the [`onbuild` Dockerfile](https://github.com/docker-library/django/blob/73c0ea2e1fbe9a34efe74128f997b3c55bf835f7/2.7/onbuild/Dockerfile) to your Dockerfile, drop the `ONBUILD` from the lines and adding a `RUN pip install --upgrade pip` just after the firsty `COPY`.

**Comment by yosifkit** [comment]
We now install an explicit version of pip in the python images so with regular pulls and rebuilds this should stay up to date.

**Comment by rodrigobraga** [comment]
:+1:
